spring:
  application:
    name: e-commerce
  profiles:
    active: test
  jpa:
    open-in-view: false
security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}
cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8100}
spring-doc:
  path-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true